---
- hosts: apic
  connection: local
  gather_facts: False
  ignore_errors: yes

  vars:
    contents: "{{lookup('file', './epgs.csv') }}"
    items: "{{ contents.split('\n')}}"
    login_info: &login_info
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_username }}"
      password: "{{ ansible_password }}"
      validate_certs: false

    #######################
    tenant: "TN-ANDRAS"
    domain: "ACI-DVS3"
    provider: "vmware"
    #provider: "microsoft"
    #######################

  tasks:
    - include_tasks: include.yaml
      with_items:
        - "{{ items }}"
      
